name: Deploy Full App to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-south-1

  ECR_BACKEND_REPO: linkedin-backend
  ECR_FRONTEND_REPO: linkedin-frontend

  ECS_CLUSTER: linkedin-cluster
  ECS_BACKEND_SERVICE: linkedin-backend-service
  ECS_FRONTEND_SERVICE: linkedin-frontend-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # ---------------- BACKEND ----------------
    - name: Build Backend Image
      run: |
        docker build -t $ECR_BACKEND_REPO ./backend
        docker tag $ECR_BACKEND_REPO:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_BACKEND_REPO:${{ github.sha }}

    - name: Push Backend Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_BACKEND_REPO:${{ github.sha }}

    # ---------------- FRONTEND ----------------
    - name: Build Frontend Image
      run: |
        docker build -t $ECR_FRONTEND_REPO ./frontend
        docker tag $ECR_FRONTEND_REPO:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${{ github.sha }}

    - name: Push Frontend Image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${{ github.sha }}

    # ---------------- DEPLOY BACKEND ----------------
    - name: Deploy Backend
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_BACKEND_SERVICE \
          --force-new-deployment

    # ---------------- DEPLOY FRONTEND ----------------
    - name: Deploy Frontend
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_FRONTEND_SERVICE \
          --force-new-deployment
